version: "3.8"
name: database
services:
  MongoDBContainer:
    image: mongo:latest
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=!Aa112233
    volumes:
      - ./mongo-init/:/docker-entrypoint-initdb.d/:ro
    ports:
      - 27117:27017

  IBMDB2Container:
    image: ibmcom/db2:latest
    restart: always
    environment:
      - LICENSE=accept
      - DB2INST1_PASSWORD=!Aa112233
      - SAMPLEDB=true
    volumes:
      - /home/db2server_fs/database:/database
    ports:
      - 50100:50000

  IBMInformixContainer:
    image: ibmcom/informix-developer-database:latest
    restart: always
    environment:
      - LICENSE=accept
      - INFORMIX_PASSWORD=!Aa112233
    ports:
      - 9188:9088